### ISSUE TITLE
'/root/.meteor' exists, but '/root/.meteor/meteor' is not executable. 

### ISSUE THREAD

**Issue by s4admin** [disney/meteor-base#113]
Have been running this in production for a long time and suddenly seeing a new issue that's breaking my builds.

'/root/.meteor' exists, but '/root/.meteor/meteor' is not executable. | Remove it and try again.

Seems it started with a recent change, even on older images.  Any advice?

**Comment by diavrank** [comment]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/39581375/169934814-67f92332-dde8-4ff7-ac7e-626e4f73bcef.png">
x2

**Comment by gregory** [comment]
@GeoffreyBooth do you have any idea what happened?  We are facing a similar issue.

**Comment by GeoffreyBooth** [comment]
I don’t know. The only recent changes were a version bump and changing the installation of `python` to `python3`, in #112. @chneau do you have any idea?

It sounds vaguely similar to the issue addressed in https://github.com/disney/meteor-base/pull/102.

**Comment by s4admin** [comment]
What's weird is that it started on Saturday without me bumping the version, and it now happens on all versions not just the latest.  It just started so I don't think it's related to code changes.  The Docker repo got a new SHA hash right around then..  I'm running in ECS if that matters, I seem to still be able to build locally.  Strange.

**Comment by nscarlson** [comment]
> What's weird is that it started on Saturday without me bumping the version, and it now happens on all versions not just the latest.  It just started so I don't think it's related to code changes.  The Docker repo got a new SHA hash right around then..  I'm running in ECS if that matters, I seem to still be able to build locally.  Strange.  

I've had this exact scenario even on other versions - suddenly builds fail, without having bumped any versions. Never been able to replicate consistently.

**Comment by GeoffreyBooth** [comment]
Whenever I merge into `main`, I rebuild and republish all the images for all the versions >= 1.9, not just the latest Meteor version. So they all get the latest `ubuntu` base image and other dependencies, so that you’re not using some years-old version of Ubuntu etc. with known security issues. The command I use is simple: `./build.sh && ./test.sh && ./push.sh`, to build all images and test all images and then push all images, but only if they all built successfully and passed the “example app” test on my local Mac. Even before merging into `main`, each new PR builds and tests all versions in GitHub actions in various environments.

So if you can replicate the issue reliably in your project, the next step is to replicate it reliably in the example app in this repo, so that we can fix it and add a test. From the looks of your screenshot, it sounds like the `docker build` stage is what’s failing, but clearly the images build on my machine and in GitHub actions; so you might need to dig a bit more to get it to fail more reliably. You could start by cloning this repo and running `./build.sh` or `CI_VERSION=2.7.1 ./build.sh` (for a particular version instead of all versions) and see if building the base image fails for you locally. Also try running `docker pull ubuntu` and then building, to ensure that you’re using the latest Ubuntu as the base image.

**Comment by s4admin** [comment]
> Whenever I merge into `main`, I rebuild and republish all the images for all the versions >= 1.9, not just the latest Meteor version.So they all get the latest ubuntu base image and other dependencies, so that you’re not using some years-old version of Ubuntu etc.

Makes sense what you're saying, but at the same time I'd rather be the one to control updates.  I think each subsequent Meteor version bring the OS updates with it, but not the priors.  If a dev wants the updates, then update they Meteor version.  Then they can test their env and make sure everything is working and release.  If my base image is suddenly updated unbeknownst to me, that could suddenly introduces an OS related incompatibility then I'm suddenly blindsided and screwed.   I guess I'll need to fork to avoid this in the future?  In the meantime still struggling to figure it out...

**Comment by JH7** [comment]
We are building on Circle CI and the fix for me was to update the machine image that we are using. I've updated from `ubuntu-2004:202010-01` to `ubuntu-2004:202201-02`. One can find the changes in https://circleci.com/docs/2.0/configuration-reference/#available-linux-machine-images, maybe there is a hint there which piece of software is failing in the first place.

I also want to give my two cents about your republishing discussion, if that's OK. I agree with both of your views, maybe there is a satisfying solution to it. Some other repositiories on Docker hub (see e.g. node https://hub.docker.com/_/node?tab=tags) add a suffix to the tag, e.g. `14-alpine3.14`. This could also be a solution here: Having one tag `2.7.2` which OS can be updated (since it is not specified in the tag) while having other tags pinning the OS version like `2.7.2-apline3.14` for example.

**Comment by GeoffreyBooth** [comment]
> @GeoffreyBooth IMO you should give back that control to the users for them to decide and rollback. Not pinning the ubuntu version in your base image exposes everyone to sudden breaking changes from ubuntu.

In my experience, company security policies generally require always using the latest version (or latest point version) of an operating system, for security. That’s the rule where I work, and I would assume this should be the default assumption.

Docker tags are mutable by design (hence the tag `latest`). If you want to pin a particular build, you can do so via the digest; for example, `FROM geoffreybooth/meteor-base:2.7.2@sha256:d860624b471bdc1340044270125ca1e1e800d2af2ae9112facc1e9ff7c9b1aae`. This would always pull that particular pushed image, regardless of whether the `2.7.2` tag points to a newer version in the future. See https://www.mikenewswanger.com/posts/2020/docker-image-digests/. Unfortunately I don't see a way to look up the history of the older digests for a particular tag; see https://forums.docker.com/t/find-all-digests-of-an-image-tag-on-a-docker-registry/90151/3. They might be in the Docker registry on your local machine, if you haven't pulled recently.

> Some other repositiories on Docker hub (see e.g. node [hub.docker.com/_/node?tab=tags](https://hub.docker.com/_/node?tab=tags)) add a suffix to the tag, e.g. `14-alpine3.14`. This could also be a solution here: Having one tag `2.7.2` which OS can be updated (since it is not specified in the tag) while having other tags pinning the OS version like `2.7.2-alpine3.14` for example.

There are multiple base images involved: `ubuntu` for building, and `node` for running. And within `node` there’s the version of Alpine _it_ uses. Pinning all of these would increase complexity very rapidly. I think using the digest is preferable, and probably the solution that the Docker designers intended for this case.

In the meantime, there’s still the question of what in the latest image broke any of you, and I would be curious to see if anyone can identify the issue.

**Comment by GeoffreyBooth** [comment]
> @GeoffreyBooth do you mind sharing the previous sha for 2.7.2 ?

I don’t have it, sorry.

**Comment by gregory** [comment]
@GeoffreyBooth any chance you could retrieve it from a previous build log?

**Comment by s4admin** [comment]
I'm not able to replicate on my Mac, it only happens on ECS Fargate instances, which makes it difficult to debug because I can't login into the image.  For now we had to fork this repo and change it to use the old ubuntu image.  Has anyone else been able to replicate in their local?

**Comment by GeoffreyBooth** [comment]
> it only happens on ECS Fargate instances

If you create an EC2 instance that you login to, does it have the issue?

One thing about Fargate insurances is that they generally have quite low memory and CPU allocations. Perhaps if you limit your local Docker similarly, it could replicate the issue?

**Comment by s4admin** [comment]
I finally figured it out.  In my ECS Environment settings the base image was an older Ubuntu base.  I had to go in there and configure the env for the updated Ubuntu base image, and make the appropriate changes to my Docker file to use AWS cli 2.0 and then everything worked fine.  This can occur if the Ubuntu base image is misaligned with the meteor-base version.  thx @GeoffreyBooth et. al. feel free to close..

**Comment by GeoffreyBooth** [comment]
@s4admin Do you mind explaining in more detail, or even better, proposing a PR to add a warning to the readme so that others know what to do if they have this issue?

And if there's some way to prevent it, like fixing the major version of Ubuntu in the `FROM` line of the build image, I would consider that too.

**Comment by s4admin** [comment]
sure...   https://github.com/disney/meteor-base/pull/115

**Comment by nscarlson** [comment]
> > @GeoffreyBooth IMO you should give back that control to the users for them to decide and rollback. Not pinning the ubuntu version in your base image exposes everyone to sudden breaking changes from ubuntu.
> 
> In my experience, company security policies generally require always using the latest version (or latest point version) of an operating system, for security. That’s the rule where I work, and I would assume this should be the default assumption.
> 
> Docker tags are mutable by design (hence the tag `latest`). If you want to pin a particular build, you can do so via the digest; for example, `FROM geoffreybooth/meteor-base:2.7.2@sha256:d860624b471bdc1340044270125ca1e1e800d2af2ae9112facc1e9ff7c9b1aae`. This would always pull that particular pushed image, regardless of whether the `2.7.2` tag points to a newer version in the future. See https://www.mikenewswanger.com/posts/2020/docker-image-digests/. Unfortunately I don't see a way to look up the history of the older digests for a particular tag; see https://forums.docker.com/t/find-all-digests-of-an-image-tag-on-a-docker-registry/90151/3. They might be in the Docker registry on your local machine, if you haven't pulled recently.

Because this project mutates existing tags, my solution to mitigate sudden breaking changes has been clone this repo, build manually in a controlled environment, and upload the images to a private Docker registry.  Mutating tags makes it impossible to depend on this project as a direct dependency, given critical stability concerns in production.

Is it possible to adopt a versioning pattern for new tags such as a suffix or namespacing such that older tags won't be overwritten?  That would benefit most people encountering this problem.

**Comment by GeoffreyBooth** [comment]
> Because this project mutates existing tags, my solution to mitigate sudden breaking changes has been clone this repo, build manually in a controlled environment, and upload the images to a private Docker registry.

I’m not sure how this is any better than pinning to the digest?

> Is it possible to adopt a versioning pattern for new tags such as a suffix or namespacing such that older tags won’t be overwritten?

The current set of tags essentially mean “this Meteor version, on the latest Ubuntu,” where the Ubuntu version gets updated periodically. I suppose we could have a tag like `2.7.2-ubuntu22.10` where I change the `FROM ubuntu` line in the base Dockerfile to `FROM ubuntu:22.10`, similar to what Node does for Alpine in its `-alpine3.15` tags (https://hub.docker.com/_/node?tab=tags&page=1&name=alpine3.15). But that doesn’t really solve the problem, because the `22.10` tag itself is a moving target, always referring to the latest 22.10.x. It would also add a lot of complexity to the building and testing of the base image, as I’d need a script to generate a _set_ of base images for each Meteor version × all supported Ubuntu versions, and test all of them. I could pin the specific version of Ubuntu in the base image but then by definition my base image would get outdated without the latest security patches.

I’m open to suggestions for new tags in addition to the current ones, but I think the existing behavior for the “Meteor version only” tags is correct, where the assumption is that the base Ubuntu is the latest version. To ship something else feels like shipping an insecure OS by default.

**Comment by GeoffreyBooth** [comment]
One idea is that I could push two tags for each image. The current one that’s just the Meteor version, and that plus the git commit hash from this repo at the commit on `main` that I’m building. So like `2.7.2` and `2.7.2-d8c08ce`. Then if/when I push a new 2.7.2 because a new PR has merged in, the `2.7.2` tag would be updated but the other one wouldn’t be, and a new tag like `2.7.2-962aec4` would be pushed.

This would provide immutable tags (the ones with the git hashes) while still preserving the current set of tags that mean “this Meteor version, with latest Ubuntu.” Would this solve anyone’s problem? Is this worth doing, when we already have essentially the same thing with Docker’s built-in digest hashes? The only advantage I can see of my `push.sh` script generating this second set of tags is that they would appear in https://hub.docker.com/r/geoffreybooth/meteor-base/tags, which currently doesn’t show digests other than the latest one for each tag.

**Comment by s4admin** [comment]
@GeoffreyBooth for me it was never my local, but my AWS code build environment.  Same error as @diavrank though.  Here is what I had to change, I changed the older environment image to the one shown in the screenshot below and then everything started working again.  Sorry I don't really deeply understand why this fixed it.  

<img width="788" alt="Screen Shot 2022-06-01 at 1 15 35 PM" src="https://user-images.githubusercontent.com/1843619/171484448-f26e5136-5923-41bf-80d8-e8eefd7a9ba1.png">

**Comment by diavrank** [comment]
@GeoffreyBooth I did the steps that you asked me but I don't have luck.

These were my existing images:

````shell
REPOSITORY                               TAG                  DIGEST                                                                    IMAGE ID       CREATED         SIZE
geoffreybooth/meteor-base   		2.7.2 	              sha256:d860624b471bdc1340044270125ca1e1e800d2af2ae9112facc1e9ff7c9b1aae   5f23013b1363   11 days ago     1.95G
node                                     14.18.3              sha256:252f6cef16c7f9abde7c10c983c02d6db8638c8caf559865a5958339b6575059   24bc96d8280c   4 months ago    944MB
ubuntu                      		16.04	              sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879   9499db781771   18 months ago   131MB
````

And I updated the ubuntu image:

````shell
root@staging-cad-psp:/opt/logos-app# docker pull ubuntu:16.04
16.04: Pulling from library/ubuntu
58690f9b18fc: Pull complete
b51569e7c507: Pull complete
da8ef40b9eca: Pull complete
fb15d46c38dc: Pull complete
Digest: sha256:20858ebbc96215d6c3c574f781133ebffdc7c18d98af4f294cc4c04871a6fe61
Status: Downloaded newer image for ubuntu:16.04
docker.io/library/ubuntu:16.04
````

This made dangling the previous image:

````shell
ubuntu                      <none>           sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879   9499db781771   18 months ago    131MB
````

So, I wanted to build again but I got the same error. Then, I wanted to delete the dangling image but it was already used for other custom images which used in my current containers, so, I removed all the dependent images and tried again but I got the same error.  Finally, I removed all my images in my docker host and I tried one more time but I got the same error :/ .

I am using a VM in GCP with **Ubuntu 16.04**, so, I created another VM with **Ubuntu 20.04** and I installed docker and docker-compose and I built again my app, and it worked

these were the digests in this new VM:

````
REPOSITORY                  TAG              DIGEST                                                                    IMAGE ID       CREATED         SIZE
geoffreybooth/meteor-base   2.7.2            sha256:d860624b471bdc1340044270125ca1e1e800d2af2ae9112facc1e9ff7c9b1aae   5f23013b1363   11 days ago     1.95GB
node                        14.19.1-alpine   sha256:8845b4f88f64f8c56a39236648ba22946e806a6153c10911f77b70e5a2edb4ca   6f5dba13ae83   8 weeks ago     119MB
ubuntu                      16.04            sha256:20858ebbc96215d6c3c574f781133ebffdc7c18d98af4f294cc4c04871a6fe61   b6f507652425   9 months ago    135MB
````

 So, I was wondering if it could be the O.S. of the host machine the cause of this problem?

**Comment by diavrank** [comment]
in case you want to reproduce it, here is my dockerfile:

````dockerfile
# The tag here should match the Meteor version of your app, per .meteor/release
FROM geoffreybooth/meteor-base:2.7.2

# Copy app package.json and package-lock.json into container
COPY ./package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY . $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh

# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 2.7.1
FROM node:14.19.1-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker
# Runtime dependencies; if your dependencies need compilation (native modules such as bcrypt) or you are using Meteor <1.8.1, use app-with-native-dependencies.dockerfile instead
RUN apk update
RUN apk upgrade
RUN apk --no-cache add \
                bash \
                g++ \
                make \
                python3

# Copy in entrypoint
COPY --from=0 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle
COPY --from=0 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source

# Start another Docker stage, so that the final image doesn’t contain the layer with the build dependencies
# See previous FROM line; this must match
FROM node:14.19.1-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker

# Install OS runtime dependencies
RUN apk --no-cache add \
        bash \
        ca-certificates \
    && update-ca-certificates

RUN apk --no-cache add --update tzdata

ENV TZ America/Mexico_City
RUN rm -rf /var/cache/apk/*

# Copy in entrypoint with the built and installed dependencies from the previous image
COPY --from=1 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle with the built and installed dependencies from the previous image
COPY --from=1 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

# Start app
ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["node", "main.js"]
````

**Comment by GeoffreyBooth** [comment]
> it could be the O.S. of the host machine the cause of this problem?

This seems to be the common element here. In @s4admin’s [comment](https://github.com/disney/meteor-base/issues/113#issuecomment-1144039147), the solution was to change the OS of the host _in which the app Docker image was built,_ which is the same as @diavrank changing from a VM with Ubuntu 16.04 to a new VM with Ubuntu 20.04. Likewise “ We are building on Circle CI and the fix for me was to update the machine image that we are using. I’ve updated from ubuntu-2004:202010-01 to ubuntu-2004:202201-02.” is also talking about changing the version of the OS building the image.

@diavrank you said you saw the issue in an Ubuntu 16.04 VM but not in an Ubuntu 20.04 VM. If you create a fresh Ubuntu 16.04 VM, where the local Docker registry has no images, and you try to build your project does it fail? If not, maybe `docker pull` a few-months-old Ubuntu image into the local Docker registry on that VM and then try to build? What I’m looking for here is some series of steps that can reproduce the problem from scratch, where the host doesn’t already have some outdated images in its local registry.

I’m not a Docker expert but I know that part of how it works is that it shares the Linux kernel of the host machine inside the containers it spawns. So maybe there’s some incompatibility between an older Ubuntu kernel and a newer Ubuntu Docker container. I’ve tried Googling a bit but I don’t see anything obvious coming up.

**Comment by diavrank** [comment]
Sure, let me check it today later and I will tell you the results

**Comment by diavrank** [comment]
@GeoffreyBooth I wanted to create a new VM with Ubuntu 16.04 but the option is no longer available in any cloud platform (I tried with GCP, Digital Ocean and AWS). They only have images from Ubuntu 18.04 :( . Besides, I wanted to reproduce the issue with an existing VM that I had in EC2 with Ubuntu 16.04 by deleting all the images from my docker host (which basically had the images for my meteor app, they were like 4 images), but I got the same error :/ . So, I guess it will be hard to reproduce again the issue in a new VM, unless I virtualize a VM in my local machine, but I wouldn't like to do that because it takes more time and also space of my disk xD, so, maybe it was time to upgrade the VMs because Ubuntu 16.04 reached its end of LTS.

I still remembered when I received an email from GCP that they were going to remove that image because it was going to be deprecated. This part of the content:

<img width="720" alt="Screen Shot 2022-06-02 at 23 22 11" src="https://user-images.githubusercontent.com/39581375/171785991-d35ff6c0-95d4-4061-8037-45b860d0ec85.png">
<img width="663" alt="Screen Shot 2022-06-02 at 23 24 29" src="https://user-images.githubusercontent.com/39581375/171785987-67d34cef-9cce-4d15-b35d-2728e5433e65.png">

**Comment by GeoffreyBooth** [comment]
I installed VirtualBox and created an Ubuntu 16 VM, installed Docker into that and cloned this repo, pulled `geoffreybooth/meteor-base:2.7.2` and ran `test.sh`. It build the example app Docker image without complaint and the test passed.

So there’s nothing inherently incompatible about Ubuntu 16. One thing I _did_ discover, doing this, was that Ubuntu 16 is deprecated and past end-of-life, and it’s really hard to install current Docker and Docker Compose on it because Docker no longer supports that version of Ubuntu. If the version of Docker any of you were using in your Ubuntu 16 images was years old, dating to when Ubuntu 16 was still supported, that might point to some incompatibility with very old versions of Docker struggling with an image built by modern Docker.

So my best guess is that the issue seems like it has something to do with an out-of-date or incompatible host operating system or old version of Docker. If anyone can provide steps to reproduce the issue, that can be followed on a new machine starting from scratch (i.e., starting with “create a new VM running X” or similar) I would be happy to investigate further; but until then, I think I’m going to close this and I’ll reopen if anyone can provide those steps.

**Comment by blacelle** [comment]
We encountered the same issue in the context if CircleCI (build was OK a year ago, a recent retry led to the described issue.)

I also feel a given `geoffreybooth/meteor-base:2.6.1` should remain as stable as possible (in term of underlying dependency/context). Even though updating the underlying UBuntu is certainly a good-thing security-wise, it should be done through a dedicated tag (e.g. `meteor-base:2.6.1` might be based on a recent UBuntu, while `meteor-base:2.6.1-ubuntu16` would be available for anybody still needing it a few years later (instead of having such unexpected issue years later) (a.k.a. dependency pinning)).

---

We successfully fixed this by updating the related stack:

1. Updating the main Docker image from `cimg/openjdk:11.0.13` to `cimg/openjdk:11.0.19` (https://circleci.com/developer/images/image/cimg/openjdk)
2. Updating the setup_remote_docker step from `19.03.13 ` to `20.10.18` (https://circleci.com/docs/2.0/building-docker-images/#docker-version)
3. Dropping the cache of `~/.meteor` folder

This was hinted but the multiple references to OS-context, and the ref to https://github.com/disney/meteor-base/pull/102#issuecomment-1063049833 (which was a very tough `bash` bug, _simply_ fixed by upgrading).
