### ISSUE TITLE
Native bcrypt requires additional command to compile on build

### ISSUE THREAD

**Issue by GuestInCorle** [disney/meteor-base#18]
Application silently crashes when `Accounts#createUser` is called.

I've cloned the latest version of your [repo](https://github.com/disney/meteor-base), added `accounts-password` Meteor package and `bcrypt` npm package, called `Accounts.createUser` server-side and expected it to work. Application crashed with no errors and traces in the logs.

I've forked to [repo](https://github.com/GuestInCorle/meteor-base) to reproduce this bug. See [README](https://github.com/GuestInCorle/meteor-base/blob/master/README.md) and last [commit](https://github.com/GuestInCorle/meteor-base/commit/27649d9919fa612b644529cb0eee12c12075cab2). Keep in mind that port `9229` is exposed and `--inspect` Node.js option is passed to be able to use chrome://inspect tool.

**Comment by GeoffreyBooth** [comment]
Thank you for the detailed report and reproduction repo. This issue was also reported in https://forums.meteor.com/t/meteor-docker-image-for-multistage-docker-builds/44908/11.

The source of the issue is the dependency you added, `bcrypt`. Per https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images:

> Alpine linux based images _use musl libc_ instead of the standard glibc and thus are _not compatible with compiled binaries_. node-pre-gyp currently does not test the pre-compiled binaries to be ABI-compatible and thus you may see segfaults. We are working to resolve this issue.
> 
> As a workaround, in Alpine based images, force recompiling the bcrypt native addon after a npm install with this command: `npm rebuild bcrypt --build-from-source`.

So we need to add `npm rebuild bcrypt --build-from-source` at the appropriate place. I see in your repo that you’re using `app-with-native-dependencies.dockerfile`, which is a good start. In that file, change the `build-meteor-npm-dependencies.sh` line to this:

```dockerfile
RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh \
	&& cd $APP_BUNDLE_FOLDER/bundle/programs/server/npm \
	&& npm rebuild --build-from-source bcrypt \
	&& apk del .node-gyp-compilation-dependencies
```

When I do this and rebuild, your app no longer crashes.

**Comment by GeoffreyBooth** [comment]
I’ve updated the base image so that using `app-with-native-dependencies.dockerfile` causes `npm rebuild --build-from-source` to be run. This means that in the future, someone following the instructions in the README should be able to just install `bcrypt` and go, without needing to discover this issue and/or edit their dockerfile.
