### ISSUE TITLE
caching .meteor/local

### ISSUE THREAD

**Issue by Maxpain177** [disney/meteor-base#20]
If .meteor/local stays persistent, build time reduces. Is it possible to cache this directory?

**Comment by GeoffreyBooth** [comment]
I don’t think so, because `.meteor/local` is generated from your app’s source code itself; and that source code presumably changes with every build.

We already cache `node_modules`, via code similar to:

```Dockerfile
COPY ./app/package*.json $APP_SOURCE_FOLDER/

RUN meteor npm install
```

The way this works, these two lines of the Dockerfile get cached until `package.json` or `package-lock.json` change, and so they get evaluated almost instantly as part of the Docker build.

You can’t do something similar with your app source itself. If you tried to do `COPY ./app/ $APP_SOURCE_FOLDER/`, that would invalidate that line and all lines below it every time your app sources change. That’s why in the Dockerfile we have, the app sources are copied in near the end.

You could have a local `.meteor/local` folder that you copy in, but then you need to have a local build environment outside of Docker capable of generating it, and the goal of this project is to avoid needing such a thing (to run in CI environments). Also your outside-of-Docker `.meteor/local` would be constantly changing as your app code does, and so there wouldn’t really be any benefit in copying it in because it would always be invalidating the cache.

If you can think of a way, I would be open to caching the folder or parts of it. This setup already caches server-side NPM dependencies under `.meteor`, so it’s not as slow as a full cold build. Ultimately though I don’t think you’re going to get a Docker build anywhere close to as fast as a local development build via the `meteor` command.

**Comment by maxpain** [comment]
I managed to cache `.meteor/local` using new `--mount=type=cache` `RUN` option of Docker BuildKit.

Here is my Dockerfile:
```Dockerfile
# It is okay to use the latest tag here because in case of a mismatch of the meteor version
# we don't have to re-download it again because we cache meteor --prepare-app step (see below)
FROM geoffreybooth/meteor-base:latest AS app
WORKDIR /src
# I use zodern:standard-minifier-js to speed-up js minification with caching in .meteor/local
# And it is important to disable stats file generation to speed up minification step
ENV DISABLE_CLIENT_STATS=true
COPY .git ./.git
COPY packages ./packages
COPY .meteor ./.meteor
# Use this undocumented feature (like npm ci) to install meteor packages without building the whole app
# to make this as a separate stage so we can cache /root/.meteor directory until any files under .meteor directory change
RUN meteor --prepare-app
COPY ./package*.json ./
RUN meteor npm ci --production
COPY . ./
# Use new cache mount feature of Docker BuildKit
RUN --mount=type=cache,target=.meteor/local meteor build --server-only --directory /

FROM node:14.19.3-slim
WORKDIR /app
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD ["node", "main.js"]
# Make sure this step is last so we don't generate extra layers
COPY --from=app /bundle ./
RUN cd programs/server && npm install --no-save --no-audit
```

.dockerignore:
```.gitignore
node_modules
Dockerfile
.*
!.meteor
!.git/modules # in case if you use git submodules to store some local meteor packages
```

Make sure to use [Docker BuildKit](https://docs.docker.com/build/buildkit/) during builds:

```bash
docker buildx build -t test-image --push .
```
or
```bash
DOCKER_BUILDKIT=1 docker build -t test-image .
```

**Comment by GeoffreyBooth** [comment]
Would you like to submit a PR?

**Comment by maxpain** [comment]
@GeoffreyBooth for readme?

**Comment by GeoffreyBooth** [comment]
You could add a new `Dockerfile` in https://github.com/disney/meteor-base/tree/main/example. I think this approach is probably only appropriate for working locally, rather than CI where Meteor and Node presumably aren’t available in the same scope as the `docker` command (and where the Meteor app isn’t already built and runnable) but for those who are running Meteor via Docker locally it would be a good option.

**Comment by maxpain** [comment]
>  I think this approach is probably only appropriate for working locally
No, I use this in GitLab CI.
