### ISSUE TITLE
PORT env has no effect

### ISSUE THREAD

**Issue by zhaoyao91** [disney/meteor-base#21]
after building a image, the meteor inside the container always runs on port 3000, even if I have set the `-e PORT=3030` or others.

**Comment by GeoffreyBooth** [comment]
You need to map the container port to your host port, for example `docker run -p 127.0.0.1:3030:3000/tcp` to map the container port 3000 to your host’s port 3030. (https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port–p—expose). See `example/docker-compose.yml` in the repo; you can run it yourself by going into `example` and starting via `docker-compose up`. That `docker-compose.yml` file maps the container port 3000 to host port 80, so that the app is accessible via http://localhost/.

Even if you were to change what port the container listens on internally, you would still need to map that to a port on the host; so even if you made Meteor run on 3030 within the container, you would need to map the container 3030 to your host’s 3030 (or whatever port you want to access the container on from your host). I don’t see what purpose this would serve, however; even if you wanted to run multiple Meteor Docker containers on the same machine, each one could listen on 3000 internally and be each mapped to separate ports on the host. Also, running the Docker image means that you need to wire up a Mongo container for it to use, hence the `docker-compose.yml` file.
