### ISSUE TITLE
Problem on change default mongo port (27017)

### ISSUE THREAD

**Issue by thearabbit** [disney/meteor-base#33]
docker-compose
```js
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: http://localhost
      MONGO_URL: mongodb://mongo:123/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    port:
      - 123:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
```

But don't work

```js
failed to connect to server [mongo:123] on first connect [Error: getaddrinfo ENOTFOUND mongo
```

**Comment by GeoffreyBooth** [comment]
```yaml
  mongo:
    port:
      - 123:27017
```

Means that _from outside of Docker,_ the `mongo` container's internal port 27017 is accessible via your host's port 123. Since `app` tries to connect from _within_ the docker-compose network, it needs to connect to `mongo:27017`.

To have `app` connect to `mongo:123`, you need to tell `mongo` to listen on port 123. That involves changing Mongo's configuration itself to listen on 123 rather than 27017; that's not a Docker configuration change. Something like:

```yaml
  mongo:
    command: --port 123
    port:
      - 123:123
```

per https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-port.

I haven't tested this; if this doesn't solve your issue, please ask on Stack Overflow. This isn't an issue related to the `meteor-base` Docker image.

**Comment by thearabbit** [comment]
Very thanks for your reply.
