### ISSUE TITLE
[Feature Request] Add support to install dependencies with Yarn

### ISSUE THREAD

**Issue by diavrank** [disney/meteor-base#57]
Hi, It would be great if the dockerfile image of meteor-base would bring installed **Yarn** in order to install dependencies with it. This is, because some developers (like me) we use yarn as package manager because it's faster than **npm**. I noticed that in these scripts use npm command:

_build-app-npm-dependencies.sh
build-meteor-npm-dependencies.sh_

So, I was looking for and I found out that it is possible to run [**meteor yarn install**](https://forums.meteor.com/t/yarn-and-meteor/30254/15?u=diavrank95) on linux systems.

So, I imagine configuring this part in the dockerfile as follow:

`ENV PACKAGE_MANAGER yarn //by default is npm`

**Comment by GeoffreyBooth** [comment]
The base image is simply downloaded from the Docker hub, so the speed of it getting built is irrelevant. In your app's image, you're free to add yarn just as you can add any other dependencies. It's not something I want to add to my example image because then the test suite would take twice as long, to test both npm and yarn.
