### ISSUE TITLE
Very slow meteor bundle

### ISSUE THREAD

**Issue by sverrirsig** [disney/meteor-base#73]
First of all, thank you for this project. It is a huge life-saver in a k8s migration I'm performing.

just wanted to get feedback on this and if it's abnormal:

I'm using the Dockerfile with native dependancies, the following step:

`Step 8/24 : RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh`

is taking a very long time (~22 minutes) in CircleCI. Granted, the project is quite large.

Is this expected or are there any suggested performance enhancers I could try out?

Thank you.

**Comment by GeoffreyBooth** [comment]
Without knowing anything about your project, I would guess it’s slow because one of your native dependencies doesn’t ship with binaries for musl/Alpine Linux and those binaries are getting compiled during install time. You could change remove the `-alpine` from the two `FROM` lines to use Ubuntu Linux instead, which your dependency is more likely to be shipping a prebuilt binary for. You could also update the dependency itself to include binaries for musl; I submitted a [PR to `node-fibers` to add support for musl binaries](https://github.com/laverdet/node-fibers/pull/384) to that, which is a dependency of Meteor itself (the acceptance of that PR was what led to me being able to support the faster, default Dockerfile that assumes no native dependencies that require compilation at install time).

**Comment by sverrirsig** [comment]
That sounds like a likely culprit. Thank you for taking the time to respond @GeoffreyBooth!
