### ISSUE TITLE
exit code 139

### ISSUE THREAD

**Issue by preethamnayak** [disney/meteor-base#9]
I am using DC/OS marathon to run meteor web app. My meteor app is crashing with status code 139, failed to accept socket loop error. Do you have any solutions ?

**Comment by FaeezBorman** [comment]
I have the same issue, It happens whenever the accounts

**Comment by GeoffreyBooth** [comment]
There are many apps that use this image successfully without the exit code issue. Therefore, I conclude that the issue must be something related to your specific app's code. If you can point to something in this image that contributes to the issue, I would be happy to look into it.

**Comment by znat** [comment]
Same for me, issue is related to bcrypt. Removing bcrypt from the dependencies (and relying on the pure js implementation) worked. However, I wouldn't call this a 'fix'
Currently on Meteor 1.8.0.2.
@GeoffreyBooth does your Meteor app use a compiled version of bcrypt or a js one?

**Comment by GeoffreyBooth** [comment]
I don’t have `bcrypt` in my app’s `package.json`, so I assume that means I’m using the JavaScript version. That’s probably safer, since I would guess that your issue is caused by your `package.json` installing the compiled version of `bcrypt` but that version can’t run in Alpine Linux. See https://github.com/kelektiv/node.bcrypt.js/issues/528

Personally I don’t find the performance gains of the natively compiled `bcrypt` worth the hassle. As far as I’m aware it’s only used for password-related operations, and I don’t have lots of users logging in or setting/changing passwords all that often.

**Comment by TeNNoX** [comment]
I want to reference here #18 - it contains instructions to fix.  
Also, just using **app-with-native-dependencies.dockerfile** will also fix this issue.

**Comment by gregory** [comment]
just ran into this - looks related to this: https://github.com/disney/meteor-base/issues/18
